services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smkpgri_app
    restart: unless-stopped
    expose:
      - '9000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=smkpgri_fee
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: smkpgri_nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: smkpgri_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smkpgri_fee
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:18-alpine
    container_name: smkpgri_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run build"

volumes:
  mysql_data:
